# Generated by Django 5.0 on 2025-11-30 14:21

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('news_type', models.CharField(choices=[('national', 'National'), ('international', 'International')], default='national', max_length=20, verbose_name="Type d'actualité")),
                ('excerpt', models.TextField(help_text="Court résumé de l'article", max_length=300, verbose_name='Résumé')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Image principale')),
                ('image_caption', models.CharField(blank=True, max_length=200, verbose_name="Légende de l'image")),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Auteur')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('source_url', models.URLField(blank=True, verbose_name='Lien source')),
                ('is_active', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher sur la page d'accueil", verbose_name='À la une')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('meta_description', models.CharField(blank=True, help_text='Description pour les moteurs de recherche', max_length=160, verbose_name='Meta description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
