# Generated by Django 5.0 on 2025-12-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('category_type', models.CharField(choices=[('architecture', 'Architecture'), ('regulation', 'Réglementation'), ('technical', 'Technique'), ('forms', 'Formulaires'), ('guides', 'Guides')], default='technical', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='library_books', help_text="Nom de l'icône Material Symbols", max_length=50, verbose_name='Icône')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Légende')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.documentcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': "Galerie d'images",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document Word'), ('xls', 'Excel'), ('ppt', 'PowerPoint'), ('zip', 'Archive ZIP')], max_length=10, verbose_name='Type de fichier')),
                ('file_size', models.CharField(blank=True, help_text='Ex: 4.2 MB', max_length=20, verbose_name='Taille du fichier')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Auteur')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.documentcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Document de référence',
                'verbose_name_plural': 'Documents de référence',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('series_name', models.CharField(blank=True, help_text='Ex: ZAFE GOUDOUGOUDOU', max_length=100, verbose_name='Nom de la série')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name="Numéro d'épisode")),
                ('description', models.TextField(verbose_name='Description')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Upload Direct')], max_length=20, verbose_name='Type de vidéo')),
                ('video_url', models.URLField(blank=True, help_text='Pour YouTube ou Vimeo', verbose_name='URL de la vidéo')),
                ('video_file', models.FileField(blank=True, help_text='Pour upload direct', upload_to='videos/%Y/%m/', verbose_name='Fichier vidéo')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/%Y/%m/', verbose_name='Miniature')),
                ('duration', models.CharField(blank=True, help_text='Ex: 15:30', max_length=20, verbose_name='Durée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.documentcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ressource vidéo',
                'verbose_name_plural': 'Ressources vidéo',
                'ordering': ['series_name', 'episode_number', 'order', '-created_at'],
            },
        ),
    ]
