# Generated by Django 5.0 on 2026-01-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentcategory_imagegallery_referencedocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='membership/%Y/%m/', verbose_name='Fichier')),
                ('file_size', models.CharField(blank=True, help_text='Ex: 2.3 MB', max_length=20, verbose_name='Taille du fichier')),
                ('icon', models.CharField(default='description', help_text="Nom de l'icône Material Symbols", max_length=50, verbose_name='Icône')),
                ('member_type', models.CharField(choices=[('national', 'Professionnels Nationaux'), ('international', 'Professionnels Internationaux'), ('both', 'Les deux')], default='both', max_length=20, verbose_name='Type de membre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Document d'adhésion",
                'verbose_name_plural': "Documents d'adhésion",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
