# Generated by Django 5.0 on 2026-01-01 10:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membershipdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie de Formation',
                'verbose_name_plural': 'Catégories de Formation',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='CategoryNorme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('icone', models.CharField(default='description', help_text="Nom de l'icône Material Symbols", max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de Norme',
                'verbose_name_plural': 'Catégories de Normes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ComiteDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('actif', models.BooleanField(default=False, help_text="Cocher si c'est le comité actuel")),
            ],
            options={
                'verbose_name': 'Comité de Direction',
                'verbose_name_plural': 'Comités de Direction',
                'ordering': ['-annee_debut'],
            },
        ),
        migrations.CreateModel(
            name='CommissionApurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('actif', models.BooleanField(default=False, help_text="Cocher si c'est la commission actuelle")),
                ('description', models.TextField(blank=True, help_text='Texte explicatif des attributions')),
            ],
            options={
                'verbose_name': "Commission d'Apurement",
                'verbose_name_plural': "Commissions d'Apurement",
                'ordering': ['-annee_debut'],
            },
        ),
        migrations.CreateModel(
            name='ConseilDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('actif', models.BooleanField(default=False, help_text="Cocher si c'est le conseil actuel")),
            ],
            options={
                'verbose_name': 'Conseil de Discipline',
                'verbose_name_plural': 'Conseils de Discipline',
                'ordering': ['-annee_debut'],
            },
        ),
        migrations.CreateModel(
            name='CotisationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='cotisation/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document de Cotisation',
                'verbose_name_plural': 'Documents de Cotisation',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Décret-loi 25 Mars 1974', max_length=200)),
                ('fichier', models.FileField(upload_to='historique/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Historique',
                'verbose_name_plural': 'Documents Historiques',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='HonneurMerite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_contenu', models.CharField(choices=[('video', 'Vidéo'), ('images', 'Images'), ('texte', 'Texte seulement')], max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Honneur et Mérite',
                'verbose_name_plural': 'Honneurs et Mérites',
                'ordering': ['-annee', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='MembreActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro d'identification unique", max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/')),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Membre Actif',
                'verbose_name_plural': 'Membres Actifs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='PageMembresActifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Liste des Ingénieurs et Architectes Actifs', max_length=200)),
                ('introduction', models.TextField(help_text="Texte d'introduction affiché en haut de la page")),
            ],
            options={
                'verbose_name': 'Configuration Page Membres Actifs',
                'verbose_name_plural': 'Configuration Page Membres Actifs',
            },
        ),
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('nom_plaignant', models.CharField(max_length=100)),
                ('email_plaignant', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('membre_concerne', models.CharField(help_text='Nom du membre visé par la plainte', max_length=200)),
                ('type_plainte', models.CharField(choices=[('ethique', "Violation d'éthique professionnelle"), ('competence', 'Compétence professionnelle'), ('qualite', 'Qualité des travaux'), ('contractuel', 'Litige contractuel'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', "En cours d'examen"), ('traitee', 'Traitée'), ('classee', 'Classée')], default='soumise', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_internes', models.TextField(blank=True, help_text='Notes pour usage interne uniquement')),
            ],
            options={
                'verbose_name': 'Plainte',
                'verbose_name_plural': 'Plaintes',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('platine', 'Platine'), ('or', 'Or'), ('argent', 'Argent'), ('bronze', 'Bronze')], max_length=20)),
                ('logo', models.ImageField(upload_to='sponsors/')),
                ('description', models.TextField(blank=True)),
                ('url_site', models.URLField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TitreProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Ingénieur Civil, Architecte, etc.', max_length=100)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Titre Professionnel',
                'verbose_name_plural': 'Titres Professionnels',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='FormationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_formation', models.DateField()),
                ('type_contenu', models.CharField(choices=[('video', 'Vidéo'), ('image', 'Image'), ('pdf', 'Document PDF'), ('groupe_images', "Groupe d'images")], max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube ou Vimeo', null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formations/')),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='core.categoryformation')),
            ],
            options={
                'verbose_name': 'Contenu de Formation',
                'verbose_name_plural': 'Contenus de Formation',
                'ordering': ['-date_formation', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='FormationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='formations/images/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.formationcontent')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='HonneurMeriteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='honneur_merite/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('honneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.honneurmerite')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(max_length=50, unique=True)),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expire', 'Expiré'), ('suspendu', 'Suspendu')], default='valide', max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.membreactif')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date_delivrance'],
            },
        ),
        migrations.CreateModel(
            name='MembreComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-Président'), ('secretaire', 'Secrétaire Général'), ('tresorier', 'Trésorier'), ('conseiller', 'Conseiller')], max_length=20)),
                ('photo', models.ImageField(upload_to='comite/')),
                ('biographie', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.comitedirection')),
            ],
            options={
                'verbose_name': 'Membre du Comité',
                'verbose_name_plural': 'Membres du Comité',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='MembreCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='commission/')),
                ('biographie', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.commissionapurement')),
            ],
            options={
                'verbose_name': 'Membre de la Commission',
                'verbose_name_plural': 'Membres de la Commission',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='MembreConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='conseil/')),
                ('biographie', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='core.conseildiscipline')),
            ],
            options={
                'verbose_name': 'Membre du Conseil',
                'verbose_name_plural': 'Membres du Conseil',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('date_publication', models.DateField()),
                ('fichier', models.FileField(upload_to='normes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('description', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normes', to='core.categorynorme')),
            ],
            options={
                'verbose_name': 'Norme',
                'verbose_name_plural': 'Normes',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPlainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='plaintes/')),
                ('nom_fichier', models.CharField(max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('plainte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.plainte')),
            ],
            options={
                'verbose_name': 'Document de Plainte',
                'verbose_name_plural': 'Documents de Plainte',
            },
        ),
        migrations.AddField(
            model_name='membreactif',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='core.titreprofessionnel'),
        ),
    ]
