# Generated by Django 5.0 on 2025-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('general', 'Information générale'), ('membership', 'Adhésion'), ('complaint', 'Plainte'), ('professional', 'Recherche de professionnel'), ('other', 'Autre')], default='general', max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('professional_type', models.CharField(choices=[('engineer', 'Ingénieur'), ('architect', 'Architecte'), ('both', 'Les deux')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de professionnel',
                'verbose_name_plural': 'Demandes de professionnels',
                'ordering': ['-created_at'],
            },
        ),
    ]
