# Generated by Django 5.0 on 2026-01-01 12:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_categoryformation_categorynorme_comitedirection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('certificat', 'Certificats'), ('formation', 'Formations'), ('reglementation', 'Réglementations'), ('template', 'Templates'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents_membres/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Membre',
                'verbose_name_plural': 'Documents Membres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ForumCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
                ('icone', models.CharField(default='forum', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de Forum',
                'verbose_name_plural': 'Catégories de Forum',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_opportunite', models.CharField(choices=[('emploi', "Offre d'emploi"), ('appel_offre', "Appel d'offres"), ('collaboration', 'Collaboration')], max_length=20)),
                ('entreprise', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('competences_requises', models.TextField()),
                ('localisation', models.CharField(max_length=200)),
                ('salaire', models.CharField(blank=True, max_length=100)),
                ('date_limite', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('fichier_joint', models.FileField(blank=True, upload_to='opportunites/')),
                ('publiee', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('membre_actif', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='core.membreactif')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur Membre',
                'verbose_name_plural': 'Utilisateurs Membres',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('preuve_paiement', models.FileField(blank=True, upload_to='cotisations/preuves/')),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ForumSujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('epingle', models.BooleanField(default=False)),
                ('verrouille', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vues', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='members.forumcategorie')),
            ],
            options={
                'verbose_name': 'Sujet de Forum',
                'verbose_name_plural': 'Sujets de Forum',
                'ordering': ['-epingle', '-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ForumReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='members.forumsujet')),
            ],
            options={
                'verbose_name': 'Réponse de Forum',
                'verbose_name_plural': 'Réponses de Forum',
                'ordering': ['date_creation'],
            },
        ),
    ]
